qua 25 dez 2024 10:58:11 -04 Vilmar Catafesta <vcatafesta@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -149,92 +149,119 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Definindo variáveis de cores
-      id: define_colors
-      shell: bash
-      run: |
-        # Definindo variáveis de cores
-        GREEN="\033[01;32m"
-        RED="\033[01;31m"
-        BLUE="\033[01;34m"
-        CYAN="\033[01;36m"
-        PINK="\033[01;35m"
-        YELLOW="\033[01;33m"
-        RESET="\033[0m"
+      - name: Definir a função send_telegram_message no script temporário
+        shell: bash
+        env:
+          TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
+          TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
+        run: |
+          #Definir a função send_telegram_message no script temporário
+          cat << 'EOF' > /tmp/send_telegram_message.sh
+          export TERM=${TERM:-xterm}
+          export TERM=${TERM:-xterm-256color}
 
-        # Usando as variáveis de cores com printf
-        printf "${GREEN}Este é um texto em verde!${RESET}\n"
-        printf "${RED}Este é um texto em vermelho!${RESET}\n"
-        printf "${BLUE}Este é um texto em azul!${RESET}\n"
-        printf "${CYAN}Este é um texto em ciano!${RESET}\n"
-        printf "${PINK}Este é um texto em rosa!${RESET}\n"
-        printf "${YELLOW}Este é um texto em amarelo!${RESET}\n"
+          #Definindo variáveis de cores
+          export red="\033[01;31m"
+          export green="\033[01;32m"
+          export yellow="\033[01;33m"
+          export blue="\033[01;34m"
+          export pink="\033[01;35m"
+          export cyan="\033[01;36m"
+          export reset="\033[0m"
+          alias ls='ls -lha --color=auto'
+          alias dir='ls -lha --color=auto'
 
-    - name: Definir a função send_telegram_message no script temporário
-      shell: bash
-      env:
-        TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
-        TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
-      run: |
-        # Definir a função send_telegram_message no script temporário
-        cat << 'EOF' > /tmp/send_telegram_message.sh
-        export TERM=${TERM:-xterm}
-        export TERM=${TERM:-xterm-256color}
+          die() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${cyan}error: ${red}${msg}${reset}"
+            exit  1
+          }
+          export -f die
 
-        # Definindo variáveis de cores
-        export green="\033[01;32m"
-        export red="\033[01;31m"
-        export blue="\033[01;34m"
-        export cyan="\033[01;36m"
-        export pink="\033[01;35m"
-        export yellow="\033[01;33m"
-        export reset="\033[0m"
+          msg_raw() {
+            local msg="$1"
+            # Remove tags HTML, se existirem
+            #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
 
-        msg() {
-          local msg="$1"
-          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-          echo -e "build-package=>${cyan}running: ${yellow}${msg}${reset}"
-        }
+            # Verifica se existe ':' na mensagem
+            if [[ "$msg" == *:* ]]; then
+              # Divide a string antes e depois do primeiro ':'
+              local before_colon="${msg%%:*}:"
+              local after_colon="${msg#*: }"
+              # Aplica as cores
+              msg="${cyan}${before_colon} ${red}${after_colon}${reset}"
+            else
+              # Se não houver ':', aplica apenas a cor padrão
+              msg="${cyan}${msg}${reset}"
+            fi
+            echo -e "$msg"
+          }
+          export -f msg_raw
 
-        msg_info() {
-          local msg="$1"
-          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-          echo -e "build-package=>${yellow}info   : ${cyan}${msg}${reset}"
-        }
+          msg() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
+          }
+          export -f msg
 
-        msg_warning() {
-          local msg="$1"
-          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-          echo -e "build-package=>${red}warning: ${orange}${msg}${reset}"
-        }
+          msg_ok() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${cyan}feito: ${green}${msg}${reset}"
+          }
+          export -f msg_ok
 
-        replicate() {
-          local char=${1:-'#'}
-          local nsize=${2:-$(tput cols)}
-          local line
-          #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
-          #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
-          printf -v line "%*s" "$nsize" && echo -e "${red}${line// /$char}${reset}"
-        }
-        export -f replicate
+          msg_run() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
+            eval "$msg"
+          }
+          export -f msg_run
 
-        send_telegram_message() {
-          local message="$1"
-          local parse_mode="$2"
+          msg_info() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${yellow}info   : ${cyan}${msg}${reset}"
+          }
+          export -f msg_info
 
-          # Define parse_mode como "MarkdownV2" se não for especificado
-          [[ -z $parse_mode ]] && parse_mode="HTML"
+          msg_warning() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${red}warning: ${orange}${msg}${reset}"
+          }
+          export -f msg_warning
 
-          # Remove as tags HTML e exibe o resultado no terminal
-          echo -e "${red}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
-          # Envia a mensagem original com HTML para o Telegram
-          curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
-            -d chat_id="${{ inputs.telegram_chat_id }}" \
-            -d text="$message" \
-            -d parse_mode="$parse_mode"
-        }
-        export -f send_telegram_message
-        EOF
+          replicate() {
+            local char=${1:-'#'}
+            local nsize=${2:-$(tput cols)}
+            local line
+            #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
+            #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
+            printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
+          }
+          export -f replicate
+
+          send_telegram_message() {
+            local message="$1"
+            local parse_mode="$2"
+
+            # Define parse_mode como "MarkdownV2" se não for especificado
+            [[ -z $parse_mode ]] && parse_mode="HTML"
+
+            # Remove as tags HTML e exibe o resultado no terminal
+            echo -e "${red}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
+            # Envia a mensagem original com HTML para o Telegram
+            curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
+              -d chat_id="${{ inputs.telegram_chat_id }}" \
+              -d text="$message" \
+              -d parse_mode="$parse_mode"
+          }
+          export -f send_telegram_message
+          EOF
 
     - name: Obter o hash do último commit do repositório remoto
       shell: bash
@@ -495,7 +522,7 @@ runs:
       run: |
         source /tmp/send_telegram_message.sh
         # Build package - Construr pacote
-        set -ex  # Isso fará o script falhar se qualquer comando falhar
+        #set -ex  # Isso fará o script falhar se qualquer comando falhar
 
         # Debug: Mostrar ambiente de build
         msg_info "Build environment: ${{ inputs.build_env }}"
@@ -531,22 +558,26 @@ runs:
           sudo chown builduser:builduser /tmp/makepkg
 
           # Extract dependencies from PKGBUILD
-          depends=$(grep -E "^depends=\(" PKGBUILD | sed 's/depends=(//' | sed 's/)$//' | tr -d "'")
-          makedepends=$(grep -E "^makedepends=\(" PKGBUILD | sed 's/makedepends=(//' | sed 's/)$//' | tr -d "'")
-
+          #depends=$(grep -E "^depends=\(" PKGBUILD | sed 's/depends=(//' | sed 's/)$//' | tr -d "'")
+          #makedepends=$(grep -E "^makedepends=\(" PKGBUILD | sed 's/makedepends=(//' | sed 's/)$//' | tr -d "'")
           # Instalar dependências
           msg_info "Installing dependencies..."
-          sudo yay -Sy --asdeps --nodeps $depends $makedepends --noconfirm
+          #sudo yay -Sy --asdeps --nodeps $depends $makedepends --noconfirm
 
           # Construir o pacote sem instalar
           msg_info "Building AUR package: ${{ inputs.package_name }}"
-          makepkg -s --noconfirm --noprogressbar --nodeps
-
-          # Mover o pacote compilado para /home/packages
-          mv *.pkg.tar.zst /home/packages/ 2>/dev/null || echo 'No package found to move'
-
-          msg "Build completed. Checking /home/packages:"
-          ls -la /home/packages
+          #if makepkg -s --noconfirm --noprogressbar --nodeps; then
+          if makepkg -s --noconfirm --noprogressbar; then
+            package_name="${{ inputs.package_name }}"
+            full_pkgname=$(find . -type f -name "$package_name*" -print)
+            echo "full_pkgname=$full_pkgname" >> $GITHUV_ENV
+            mv "$full_pkgname" /home/packages/ 2>/dev/null || echo 'No package found to move'
+            msg "Build completed. Checking /home/packages:"
+            ls -la /home/packages
+          else
+            msg_warning "Build makepkg fail."
+            exit 1
+          fi
         else
           # Para pacotes não-AUR
           gitfolder=$(find . -name "PKGBUILD" -exec dirname {} \;)
