qui 26 dez 2024 21:16:11 -04 Vilmar Catafesta <vcatafesta@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -387,24 +387,26 @@ runs:
         sudo sed -i '/biglinux/,$d' /etc/pacman.conf
 
         msg_info "#Add repositories on build environment"
-        entries=(
-          "[chili-stable]=https://repo.chililinux.com/stable/\$arch"
-          "[chili-testing]=https://repo.chililinux.com/testing/\$arch"
-          "[chili-extra]=https://repo.chililinux.com/extra/\$arch"
-          "[community-stable]=https://repo.communitybig.org/stable/\$arch"
-          "[community-testing]=https://repo.communitybig.org/testing/\$arch"
-          "[community-extra]=https://repo.communitybig.org/extra/\$arch"
-          "[biglinux-stable]=https://repo.biglinux.com.br/stable/\$arch"
-          "[biglinux-testing]=https://repo.biglinux.com.br/testing/\$arch"
+        declare -A entries=(
+          [chili-stable]='https://repo.chililinux.com/stable/$arch'
+          [chili-testing]='https://repo.chililinux.com/testing/$arch'
+          [chili-extra]='https://repo.chililinux.com/extra/$arch'
+          [community-stable]='https://repo.communitybig.org/stable/$arch'
+          [community-testing]='https://repo.communitybig.org/testing/$arch'
+          [community-extra]='https://repo.communitybig.org/extra/$arch'
+          [biglinux-stable]='https://repo.biglinux.com.br/stable/$arch'
+          [biglinux-testing]='https://repo.biglinux.com.br/testing/$arch'
+          [vilmar-testing]='https://repo.biglinux.com.br/testing/$arch'
         )
 
-        for entry in "${entries[@]}"; do
-          section="${entry%%=*}" # Extrai a seção (antes do "=")
-          server="${entry#*=}"   # Extrai o servidor (depois do "=")
+        for entry in "${!entries[@]}"; do
+          section='['"$entry"']'
+          server="${entries[$entry]}"
 
-          if ! grep -q "$section" /etc/pacman.conf; then
-            echo -e "\n$section\nSigLevel = PackageRequired\nServer = $server\n" | \
+          if ! grep -qF "$section" /etc/pacman.conf; then
+            echo -e "\n$section\nSigLevel = PackageRequired\nServer = $server" | \
             sudo tee -a /etc/pacman.conf /etc/chrootbuild/pacman.conf.x86_64 >/dev/null
+            msg_info "Added section: $section"
           fi
         done
 
