qua 25 dez 2024 11:01:42 -04 Vilmar Catafesta <vcatafesta@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -149,119 +149,119 @@ inputs:
 runs:
   using: "composite"
   steps:
-      - name: Definir a função send_telegram_message no script temporário
-        shell: bash
-        env:
-          TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
-          TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
-        run: |
-          #Definir a função send_telegram_message no script temporário
-          cat << 'EOF' > /tmp/send_telegram_message.sh
-          export TERM=${TERM:-xterm}
-          export TERM=${TERM:-xterm-256color}
+    - name: Definir a função send_telegram_message no script temporário
+      shell: bash
+      env:
+        TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
+        TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
+      run: |
+        #Definir a função send_telegram_message no script temporário
+        cat << 'EOF' > /tmp/send_telegram_message.sh
+        export TERM=${TERM:-xterm}
+        export TERM=${TERM:-xterm-256color}
 
-          #Definindo variáveis de cores
-          export red="\033[01;31m"
-          export green="\033[01;32m"
-          export yellow="\033[01;33m"
-          export blue="\033[01;34m"
-          export pink="\033[01;35m"
-          export cyan="\033[01;36m"
-          export reset="\033[0m"
-          alias ls='ls -lha --color=auto'
-          alias dir='ls -lha --color=auto'
+        #Definindo variáveis de cores
+        export red="\033[01;31m"
+        export green="\033[01;32m"
+        export yellow="\033[01;33m"
+        export blue="\033[01;34m"
+        export pink="\033[01;35m"
+        export cyan="\033[01;36m"
+        export reset="\033[0m"
+        alias ls='ls -lha --color=auto'
+        alias dir='ls -lha --color=auto'
 
-          die() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${cyan}error: ${red}${msg}${reset}"
-            exit  1
-          }
-          export -f die
+        die() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${cyan}error: ${red}${msg}${reset}"
+          exit  1
+        }
+        export -f die
 
-          msg_raw() {
-            local msg="$1"
-            # Remove tags HTML, se existirem
-            #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
+        msg_raw() {
+          local msg="$1"
+          # Remove tags HTML, se existirem
+          #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
 
-            # Verifica se existe ':' na mensagem
-            if [[ "$msg" == *:* ]]; then
-              # Divide a string antes e depois do primeiro ':'
-              local before_colon="${msg%%:*}:"
-              local after_colon="${msg#*: }"
-              # Aplica as cores
-              msg="${cyan}${before_colon} ${red}${after_colon}${reset}"
-            else
-              # Se não houver ':', aplica apenas a cor padrão
-              msg="${cyan}${msg}${reset}"
-            fi
-            echo -e "$msg"
-          }
-          export -f msg_raw
+          # Verifica se existe ':' na mensagem
+          if [[ "$msg" == *:* ]]; then
+            # Divide a string antes e depois do primeiro ':'
+            local before_colon="${msg%%:*}:"
+            local after_colon="${msg#*: }"
+            # Aplica as cores
+            msg="${cyan}${before_colon} ${red}${after_colon}${reset}"
+          else
+            # Se não houver ':', aplica apenas a cor padrão
+            msg="${cyan}${msg}${reset}"
+          fi
+          echo -e "$msg"
+        }
+        export -f msg_raw
 
-          msg() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
-          }
-          export -f msg
+        msg() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
+        }
+        export -f msg
 
-          msg_ok() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${cyan}feito: ${green}${msg}${reset}"
-          }
-          export -f msg_ok
+        msg_ok() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${cyan}feito: ${green}${msg}${reset}"
+        }
+        export -f msg_ok
 
-          msg_run() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
-            eval "$msg"
-          }
-          export -f msg_run
+        msg_run() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${cyan}running: ${yellow}${msg}${reset}"
+          eval "$msg"
+        }
+        export -f msg_run
 
-          msg_info() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${yellow}info   : ${cyan}${msg}${reset}"
-          }
-          export -f msg_info
+        msg_info() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${yellow}info   : ${cyan}${msg}${reset}"
+        }
+        export -f msg_info
 
-          msg_warning() {
-            local msg="$1"
-            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
-            echo -e "BIV=>${red}warning: ${orange}${msg}${reset}"
-          }
-          export -f msg_warning
+        msg_warning() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BIV=>${red}warning: ${orange}${msg}${reset}"
+        }
+        export -f msg_warning
 
-          replicate() {
-            local char=${1:-'#'}
-            local nsize=${2:-$(tput cols)}
-            local line
-            #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
-            #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
-            printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
-          }
-          export -f replicate
+        replicate() {
+          local char=${1:-'#'}
+          local nsize=${2:-$(tput cols)}
+          local line
+          #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
+          #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
+          printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
+        }
+        export -f replicate
 
-          send_telegram_message() {
-            local message="$1"
-            local parse_mode="$2"
+        send_telegram_message() {
+          local message="$1"
+          local parse_mode="$2"
 
-            # Define parse_mode como "MarkdownV2" se não for especificado
-            [[ -z $parse_mode ]] && parse_mode="HTML"
+          # Define parse_mode como "MarkdownV2" se não for especificado
+          [[ -z $parse_mode ]] && parse_mode="HTML"
 
-            # Remove as tags HTML e exibe o resultado no terminal
-            echo -e "${red}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
-            # Envia a mensagem original com HTML para o Telegram
-            curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
-              -d chat_id="${{ inputs.telegram_chat_id }}" \
-              -d text="$message" \
-              -d parse_mode="$parse_mode"
-          }
-          export -f send_telegram_message
-          EOF
+          # Remove as tags HTML e exibe o resultado no terminal
+          echo -e "${red}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
+          # Envia a mensagem original com HTML para o Telegram
+          curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
+            -d chat_id="${{ inputs.telegram_chat_id }}" \
+            -d text="$message" \
+            -d parse_mode="$parse_mode"
+        }
+        export -f send_telegram_message
+        EOF
 
     - name: Obter o hash do último commit do repositório remoto
       shell: bash
